### ISSUE TITLE
Unknown props issue

### ISSUE THREAD

**Issue by Borisboky** [FormidableLabs/react-shuffle#26]
I have an issue with props. My render method is something like this : 

```
render() {
        const language = this.props.language.default.portal;
        const cars = this.props.cars;
        const favorites = this.props.favorites;
        const cartContent = this.props.cartContent;
        const addToFavorites = this.props.addToFavorites;
        const removeFromCard = this.props.removeFromCard;
        const addToCard = this.props.addToCard;
        const handleOffers = this.props.handleOffers;
        const offers = this.props.offers;
        const currentUserEmail = getUserEmail();

        return (
            <div className="cars">
                    <div>
                        <Shuffle>
                        {cars.map((car, i) => {
                            const initialReg = car.initialRegistration.slice(0,3) + car.initialRegistration.slice(6,10);
                            // str.slice(1, 4) extracts the second character through the fourth character (characters indexed 1, 2, and 3)

                            return (
                                <div key={i} className="carBox noPadding">
                                    <div className="carBoxContent">

                                        <PhotoAndFavorites car={car} language={language} changeStarIcon={this.changeStarIcon} addToFavorites={addToFavorites} userEmail={currentUserEmail} favorites={favorites}/>

                                        <div className="carNameAndDesc">
                                            <div><Link to="" style={{textDecoration: 'none'}}>{car.make}</Link></div>
                                            <div>{car.desc}</div>
                                        </div>

                                        <div className="carPrice">
                                            <div>{car.price}</div>
                                            <div>{car.btw}</div>
                                        </div>

                                        <div className="extraFeatures" style={{marginBottom: 5, backgroundColor: '#eee'}}>

                                        </div>

                                        <div className="mainFeatures">
                                            <div><img src="../images/portal/user/status/fuel-icon.png" style={{height: 12}}/> <span>{car.fuel}</span></div>
                                            <div><img src="../images/portal/user/status/road-icon.png" style={{height: 12}}/> <span>{car.mileage}</span></div>
                                            <div><img src="../images/portal/user/status/calendar-icon.png" style={{height: 12}}/> <span>{initialReg}</span></div>
                                        </div>

                                        <Buttons car={car}
                                                 language={language}
                                                 changeButton={this.changeButton}
                                                 addToCard={addToCard}
                                                 removeFromCard={removeFromCard}
                                                 cartContent={cartContent}
                                                 userEmail={currentUserEmail}
                                                 handleChange={handleOffers}
                                                 offers={offers}
                                                 opacity={this.props.opacity}
                                                 />

                                    </div>
                                </div>
                            );
                        })}
                        </Shuffle>
                    </div>
                <div className="clearfix"/>
            </div>
        );
    }
```

But the animation doesn't happening and I'm getting warning 
**bundle.js:8394 Warning: Unknown props `duration`, `fade`, `initial` on div tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop**

**Comment by marcelopereirascmspain** [comment]
Hi, this issue is fixed by https://github.com/FormidableLabs/react-shuffle/pull/25
Waiting for 2.0.1 bump

**Comment by Borisboky** [comment]
My package.json is something like : 

```
"dependencies": {
    "classnames": "^2.2.5",
    "lodash": "^4.13.1",
    "react": "^15.1.0",
    "react-addons-css-transition-group": "^15.3.1",
    "react-dom": "^15.1.0",
    "react-fontawesome": "^1.1.0",
    "react-icons": "^2.2.1",
    "react-redux": "^4.4.5",
    "react-router": "^2.4.1",
    "react-shuffle": "^2.0.0",
    "react-slick": "^0.13.3",
    "react-telephone-input": "^3.4.6",
    "redux": "^3.5.2",
    "redux-thunk": "^2.1.0"
  },
  "devDependencies": {
    "babel-plugin-transform-object-rest-spread": "^6.8.0",
    "babel-preset-es2015": "^6.9.0",
    "babel-preset-react": "^6.5.0",
    "babel-preset-stage-0": "^6.5.0",
    "babelify": "^7.3.0",
    "browserify": "^13.0.1",
    "crypto-js": "^3.1.6",
    "eslint-plugin-react": "^6.2.0",
    "gulp": "^3.9.1",
    "gulp-browserify": "^0.5.1",
    "gulp-concat": "^2.6.0",
    "gulp-connect": "^5.0.0",
    "gulp-eslint": "^3.0.1",
    "gulp-open": "^2.0.0",
    "gulp-sass": "^2.3.1",
    "lodash": "^4.15.0",
    "merge-stream": "^1.0.0",
    "react-addons-css-transition-group": "^15.3.1",
    "reactify": "^1.1.1",
    "vinyl-source-stream": "^1.1.0"
  }
```

And the render in src/shuffle.js is something like : 

```
render() {
    let { initial, fade, duration, ...props } = this.props;
    var showContainer = initial ? 0 : 1;
    if (this.state.ready) {
      showContainer = 0;
    }
    return (
      <div ref="container" style={{position: 'relative'}} {...this.props}>
        <div style={{opacity: showContainer}}>
          {this._childrenWithRefs()}
        </div>
      </div>
    );
  }

```

But the warning still exists.

**Comment by Borisboky** [comment]
Any idea why this is not working?

**Comment by soetji** [comment]
When will this fix available on npm?

**Comment by marcelopereirascmspain** [comment]
@kenwheeler could you publish the module with the new fixes? Thanks.

**Comment by joshgagnon** [comment]
The lib folder needs to be recompiled, that is all.

**Comment by svnlto** [comment]
If @kenwheeler could publish this. would be fantastic..
